### ISSUE TITLE
Review MEE worked example output

### ISSUE THREAD

**Issue by schafnoir** [NEONScience/mee-tos-2022#2]
@fluby @SaraPaull @gitbarnitt @cklunch 

Hi folks,
You all have been directly or tangentially involved with or aware of the Methods in Ecology & Evolution manuscript that was returned for revisions. The Worked Example output is now ready for review by co-authors (needed), or for review by esteemed colleagues (much appreciated if you have time). It might make the most sense to open up and review the html output, as this will be what I think most readers of the manuscript will do.

Cheers and many thanks!
CM

**Comment by schafnoir** [comment]
Note: If you want to try running the code (which is also an obvious thing to do), it knitted just fine for me, so fingers crossed it'll do the same for you!

**Comment by gitbarnitt** [comment]
@schafnoir some initial comments:

- I suggest you consider a bit more information in the Introduction. Why might you want to do this, i.e., what are some of the questions that could be asked of this integration? 

- Similarly, you might want to include a bit more about the differences in both temporal and spatial scale, how plots are collocated and why scientific insight is likely still possible given these differences. If you don't include the site schematic figure you created long ago, maybe cite Thorpe et al here?

- Some of the above is included in the Load CDW section, but it might benefit from a change in section name (much of this is more about the data than loading it in R), a bit more about the methods, and either moving the mammal description to another section or moving this text to the intro or a new section. 


- Otherwise this is super, really neat to see the figures at the end!

**Comment by schafnoir** [comment]
@gitbarnitt - many thanks for the feedback! I'll work on adding a bit more context to the text part of the Rmd
